// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmlylqgfjaawubgmskkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbHlscWdmamFhd3ViZ21za2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTM3MTMsImV4cCI6MjA5MDYyOTcxM30.irQ5xdlQJslV-PBLgZgpxlq9IV7Y4KrLPhEOsxlw6es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});